; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E4728419-DA43-4B14-BD40-274D49DA8B78}
AppName=Faran Nexus ERP
AppVersion=1.0
;AppVerName=Faran Nexus ERP 1.0
AppPublisher=Yousaf Atiq
DefaultDirName={autopf}\Faran Nexus ERP
UninstallDisplayIcon={app}\launcher.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=D:\Medicine_ERP\Faran_Nexus_Setup
OutputBaseFilename=Faran_Nexus_Setup
SetupIconFile=D:\Medicine_ERP\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Medicine_ERP\dist\launcher\launcher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Medicine_ERP\db.sqlite3"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-modify
Source: "D:\Medicine_ERP\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Medicine_ERP\dist\backend_server\*"; DestDir: "{app}\backend_server"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Medicine_ERP\desktop-app\dist\*"; DestDir: "{app}\desktop-app\dist"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Medicine_ERP\dist\launcher\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Faran Nexus ERP"; Filename: "{app}\launcher.exe"
Name: "{autodesktop}\Faran Nexus ERP"; Filename: "{app}\launcher.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\launcher.exe"; Description: "{cm:LaunchProgram,Faran Nexus ERP}"; Flags: nowait postinstall skipifsilent

