# Generated by Django 6.0.4 on 2026-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
